% compatible(hero1,hero2)
% hero1 is compatible with hero2 as a team member.
compatible(miya,tigreal).
compatible(miya,belerick).
compatible(gusion,vexana).
compatible(gusion,pharsa).
compatible(kalea,eudora).
compatible(kalea,harley).
compatible(kalea,clint).
compatible(chip,alpha).
compatible(chip,hanabi).
compatible(chip,kadita).
compatible(floryn,terizla).
compatible(floryn,thamuz).
compatible(mathilda,saber).
compatible(mathilda,eudora).
compatible(carmilla,cecilion).
compatible(carmilla,aurora).
compatible(faramis,leomord).
compatible(faramis,martis).
compatible(kaja,eudora).
compatible(kaja,aamon).
compatible(angela,lancelot).
compatible(angela,aamon).
compatible(diggie,layla).
compatible(diggie,miya).
compatible(estes,lesley).
compatible(estes,hanabi).
compatible(johnson,odette).
compatible(johnson,kadita).
compatible(lolita,hanabi).
compatible(lolita,layla).
compatible(minotaur,granger).
compatible(minotaur,melissa).
compatible(rafaela,freya).
compatible(rafaela,lapu_lapu).
compatible(obsidia,angela).
compatible(obsidia,estes).
compatible(zetian,floryn).
compatible(zetian,rafaela).
compatible(ixia,fredrinn).
compatible(ixia,bane).
compatible(melissa,tigreal).
compatible(melissa,minotaur).
compatible(edith,minotaur).
compatible(edith,atlas).
compatible(natan,johnson).
compatible(natan,alpha).
compatible(beatrix,khufra).
compatible(beatrix,atlas).
compatible(brody,hylos).
compatible(brody,minsitthar).
compatible(popol_and_kupa,alpha).
compatible(popol_and_kupa,khaleed).
compatible(wanwan,franco).
compatible(wanwan,belerick).
compatible(granger,franco).
compatible(granger,kaja).
compatible(kimmy,badang).
compatible(kimmy,ruby).
compatible(claude,angela).
compatible(claude,faramis).
compatible(hanabi,carmilla).
compatible(hanabi,atlas).
compatible(lesley,minotaur).
compatible(lesley,baxia).
compatible(irithel,valir).
compatible(irithel,hylos).
compatible(karrie,aamon).
compatible(karrie,saber).
compatible(roger,hanabi).
compatible(roger,odette).
compatible(moskov,fredrinn).
compatible(moskov,gatotkaca).
compatible(yi_sun_shin,alpha).
compatible(yi_sun_shin,khaleed).
compatible(layla,minsitthar).
compatible(layla,belerick).
compatible(clint,rafaela).
compatible(clint,angela).
compatible(bruno,franco).
compatible(bruno,khufra).
compatible(miya,tigreal).
compatible(miya,belerick).
compatible(zhuxin,cici).
compatible(zhuxin,kimmy).
compatible(zhuxin,belerick).
compatible(novaria,beatrix).
compatible(novaria,layla).
compatible(xavier,carmilla).
compatible(xavier,atlas).
compatible(valentina,carmilla).
compatible(valentina,atlas).
compatible(yve,minotaur).
compatible(yve,gatotkaca).
compatible(yve,atlas).
compatible(luo_yi,aamon).
compatible(luo_yi,karina).
compatible(cecilion,carmilla).
compatible(cecilion,minotaur).
compatible(lylia,minotaur).
compatible(lylia,franco).
compatible(esmeralda,atlas).
compatible(esmeralda,tigreal).
compatible(faramis,leomord).
compatible(faramis,martis).
compatible(kadita,atlas).
compatible(kadita,tigreal).
compatible(harith,minsitthar).
compatible(harith,minotaur).
compatible(lunox,franco).
compatible(lunox,minotaur).
compatible(vale,lolita).
compatible(vale,belerick).
compatible(selena,xavier).
compatible(selena,beatrix).
compatible(chang_e,gatotkaca).
compatible(chang_e,tigreal).
compatible(valir,khaleed).
compatible(valir,yu_zhong).
compatible(pharsa,atlas).
compatible(pharsa,franco).
compatible(zhask,belerick).
compatible(zhask,lolita).
compatible(odette,johnson).
compatible(odette,jawhead).
compatible(harley,akai).
compatible(harley,khufra).
compatible(vexana,atlas).
compatible(vexana,beatrix).
compatible(aurora,ixia).
compatible(aurora,freya).
compatible(aurora,karrie).
compatible(cyclops,belerick).
compatible(cyclops,minsitthar).
compatible(kagura,tigreal).
compatible(kagura,atlas).
compatible(gord,hylos).
compatible(gord,belerick).
compatible(eudora,johnson).
compatible(eudora,jawhead).
compatible(bane,tigreal).
compatible(bane,luo_yi).
compatible(nana,rafaela).
compatible(nana,franco).
compatible(alice,balmond).
compatible(alice,dyrroth).
compatible(suyou,rafaela).
compatible(suyou,tigreal).
compatible(nolan,tigreal).
compatible(nolan,gatotkaca).
compatible(arlott,gatotkaca).
compatible(arlott,atlas).
compatible(joy,angela).
compatible(joy,hylos).
compatible(julian,angela).
compatible(julian,diggie).
compatible(yin,mathilda).
compatible(yin,rafaela).
compatible(aamon,rafaela).
compatible(aamon,floryn).
compatible(paquito,angela).
compatible(paquito,rafaela).
compatible(benedetta,johnson).
compatible(benedetta,gatotkaca).
compatible(ling,angela).
compatible(ling,khufra).
compatible(hanzo,aurora).
compatible(hanzo,belerick).
compatible(hanzo,tigreal).
compatible(helcurt,tigreal).
compatible(helcurt,esmeralda).
compatible(helcurt,terizla).
compatible(lancelot,atlas).
compatible(lancelot,tigreal).
compatible(natalia,yi_sun_shin).
compatible(natalia,vexana).
compatible(hayabusa,lapu_lapu).
compatible(hayabusa,alpha).
compatible(fanny,minotaur).
compatible(fanny,gatotkaca).
compatible(zilong,pharsa).
compatible(zilong,hanabi).
compatible(karina,tigreal).
compatible(karina,faramis).
compatible(alucard,gatotkaca).
compatible(alucard,xavier).
compatible(saber,kadita).
compatible(saber,cyclops).
compatible(lukas,atlas).
compatible(lukas,tigreal).
compatible(lukas,gatotkaca).
compatible(cici,angela).
compatible(cici,floryn).
compatible(aulus,angela).
compatible(aulus,yve).
compatible(fredrinn,floryn).
compatible(fredrinn,angela).
compatible(phoveus,gatotkaca).
compatible(phoveus,minotaur).
compatible(phoveus,tigreal).
compatible(barats,mathilda).
compatible(barats,angela).
compatible(yu_zhong,vexana).
compatible(yu_zhong,xavier).
compatible(khaleed,roger).
compatible(khaleed,karina).
compatible(silvanna,atlas).
compatible(silvanna,tigreal).
compatible(masha,angela).
compatible(masha,rafaela).
compatible(dyrroth,franco).
compatible(dyrroth,kaja).
compatible(x_borg,karina).
compatible(x_borg,martis).
compatible(terizla,gatotkaca).
compatible(terizla,atlas).
compatible(guinevere,franco).
compatible(guinevere,hylos).
compatible(badang,tigreal).
compatible(badang,luo_yi).
compatible(minsitthar,melissa).
compatible(minsitthar,hanabi).
compatible(thamuz,angela).
compatible(thamuz,rafaela).
compatible(leomord,pharsa).
compatible(leomord,vexana).
compatible(aldous,balmond).
compatible(aldous,bruno).
compatible(martis,alpha).
compatible(martis,khaleed).
compatible(jawhead,odette).
compatible(jawhead,belerick).
compatible(argus,angela).
compatible(argus,rafaela).
compatible(sun,belerick).
compatible(sun,tigreal).
compatible(chou,angela).
compatible(chou,rafaela).
compatible(freya,belerick).
compatible(freya,gatotkaca).
compatible(balmond,angela).
compatible(balmond,rafaela).
compatible(gloo,eudora).
compatible(gloo,saber).
compatible(atlas,vale).
compatible(atlas,ixia).
compatible(grock,odette).
compatible(grock,pharsa).
compatible(gatotkaca,kagura).
compatible(gatotkaca,vale).
compatible(lapu_lapu,tigreal).
compatible(lapu_lapu,atlas).
compatible(hilda,rafaela).
compatible(hilda,franco).
compatible(ruby,pharsa).
compatible(ruby,kadita).
compatible(alpha,vexana).
compatible(alpha,selena).
compatible(baxia,thamuz).
compatible(baxia,alpha).
compatible(khufra,eudora).
compatible(khufra,pharsa).
compatible(belerick,natan).
compatible(belerick,miya).
compatible(uranus,beatrix).
compatible(uranus,hanabi).
compatible(hylos,terizla).
compatible(hylos,minsitthar).
compatible(franco,vale).
compatible(franco,karina).
compatible(franco,brody).
compatible(akai,saber).
compatible(akai,eudora).
compatible(tigreal,vexana).
compatible(tigreal,odette).