% iscounter(hero1,hero2).
% hero1 is a counter to hero2.
iscounter(kalea,layla).
iscounter(kalea,chang_e).
iscounter(obsidia,hayabusa).
iscounter(obsidia,freya).
iscounter(obsidia,lancelot).
iscounter(zetian,balmond).
iscounter(zetian,zilong).
iscounter(lukas,hanabi).
iscounter(lukas,ixia).
iscounter(suyou,ixia).
iscounter(suyou,xavier).
iscounter(zhuxin,popol_and_kupa).
iscounter(zhuxin,cyclops).
iscounter(chip,vexana).
iscounter(chip,layla).
iscounter(chip,ixia).
iscounter(cici,fredrinn).
iscounter(cici,minotaur).
iscounter(nolan,hanabi).
iscounter(nolan,eudora).
iscounter(ixia,fredrinn).
iscounter(ixia,bane).
iscounter(arlott,sun).
iscounter(arlott,zilong).
iscounter(novaria,eudora).
iscounter(novaria,odette).
iscounter(joy,xavier).
iscounter(joy,vexana).
iscounter(fredrinn,vale).
iscounter(fredrinn,eudora).
iscounter(julian,cecilion).
iscounter(julian,aldous).
iscounter(xavier,hanabi).
iscounter(xavier,faramis).
iscounter(melissa,sun).
iscounter(melissa,zilong).
iscounter(yin,layla).
iscounter(yin,cecilion).
iscounter(floryn,uranus).
iscounter(floryn,lolita).
iscounter(edith,zilong).
iscounter(edith,aulus).
iscounter(valentina,hanabi).
iscounter(valentina,faramis).
iscounter(aamon,xavier).
iscounter(aamon,cecilion).
iscounter(aulus,hanabi).
iscounter(aulus,yve).
iscounter(aulus,gord).
iscounter(natan,tigreal).
iscounter(natan,gatotkaca).
iscounter(phoveus,wanwan).
iscounter(phoveus,arlott).
iscounter(phoveus,chou).
iscounter(beatrix,hylos).
iscounter(beatrix,belerick).
iscounter(gloo,cecilion).
iscounter(gloo,chang_e).
iscounter(paquito,gord).
iscounter(paquito,layla).
iscounter(mathilda,gord).
iscounter(mathilda,vale).
iscounter(yve,fredrinn).
iscounter(yve,barats).
iscounter(yve,aulus).
iscounter(brody,aamon).
iscounter(brody,yin).
iscounter(barats,belerick).
iscounter(barats,lolita).
iscounter(khaleed,cyclops).
iscounter(khaleed,xavier).
iscounter(benedetta,jawhead).
iscounter(benedetta,guinevere).
iscounter(luo_yi,eudora).
iscounter(luo_yi,gord).
iscounter(yu_zhong,aulus).
iscounter(yu_zhong,zilong).
iscounter(popol_and_kupa,lesley).
iscounter(popol_and_kupa,brody).
iscounter(atlas,vexana).
iscounter(atlas,eudora).
iscounter(carmilla,dyrroth).
iscounter(carmilla,lapu_lapu).
iscounter(cecilion,balmond).
iscounter(cecilion,terizla).
iscounter(silvanna,layla).
iscounter(silvanna,valir).
iscounter(wanwan,fredrinn).
iscounter(wanwan,luo_yi).
iscounter(masha,ixia).
iscounter(masha,layla).
iscounter(baxia,chang_e).
iscounter(baxia,silvanna).
iscounter(lylia,carmilla).
iscounter(lylia,hylos).
iscounter(dyrroth,gord).
iscounter(dyrroth,hanabi).
iscounter(ling,layla).
iscounter(ling,hanabi).
iscounter(x_borg,terizla).
iscounter(x_borg,aulus).
iscounter(terizla,zilong).
iscounter(terizla,sun).
iscounter(esmeralda,akai).
iscounter(esmeralda,lolita).
iscounter(guinevere,zilong).
iscounter(guinevere,silvanna).
iscounter(granger,chang_e).
iscounter(granger,cecilion).
iscounter(khufra,joy).
iscounter(khufra,lancelot).
iscounter(badang,layla).
iscounter(badang,odette).
iscounter(faramis,saber).
iscounter(faramis,eudora).
iscounter(kadita,aurora).
iscounter(kadita,eudora).
iscounter(minsitthar,benedetta).
iscounter(minsitthar,arlott).
iscounter(harith,belerick).
iscounter(harith,johnson).
iscounter(thamuz,zilong).
iscounter(thamuz,sun).
iscounter(kimmy,granger).
iscounter(kimmy,cecilion).
iscounter(belerick,lancelot).
iscounter(belerick,ling).
iscounter(hanzo,layla).
iscounter(hanzo,ixia).
iscounter(hanzo,zhuxin).
iscounter(lunox,yve).
iscounter(lunox,lylia).
iscounter(leomord,odette).
iscounter(leomord,pharsa).
iscounter(leomord,yve).
iscounter(leomord,cecilion).
iscounter(vale,terizla).
iscounter(vale,hilda).
iscounter(claude,vexana).
iscounter(claude,floryn).
iscounter(aldous,zilong).
iscounter(aldous,leomord).
iscounter(selena,gord).
iscounter(selena,layla).
iscounter(kaja,fanny).
iscounter(kaja,lancelot).
iscounter(chang_e,eudora).
iscounter(chang_e,odette).
iscounter(hanabi,tigreal).
iscounter(hanabi,belerick).
iscounter(uranus,tigreal).
iscounter(uranus,franco).
iscounter(martis,layla).
iscounter(martis,odette).
iscounter(valir,balmond).
iscounter(valir,fredrinn).
iscounter(gusion,layla).
iscounter(gusion,hanabi).
iscounter(angela,uranus).
iscounter(angela,belerick).
iscounter(jawhead,eudora).
iscounter(jawhead,saber).
iscounter(lesley,gatotkaca).
iscounter(lesley,fredrinn).
iscounter(pharsa,layla).
iscounter(pharsa,hanabi).
iscounter(pharsa,xavier).
iscounter(helcurt,layla).
iscounter(helcurt,chang_e).
iscounter(helcurt,vale).
iscounter(zhask,aldous).
iscounter(zhask,paquito).
iscounter(hylos,layla).
iscounter(hylos,gord).
iscounter(diggie,atlas).
iscounter(diggie,lolita).
iscounter(lancelot,cecilion).
iscounter(lancelot,pharsa).
iscounter(odette,layla).
iscounter(odette,irithel).
iscounter(argus,gord).
iscounter(argus,aurora).
iscounter(grock,gord).
iscounter(grock,layla).
iscounter(irithel,miya).
iscounter(irithel,alpha).
iscounter(harley,ixia).
iscounter(harley,cecilion).
iscounter(gatotkaca,layla).
iscounter(gatotkaca,popol_and_kupa).
iscounter(karrie,tigreal).
iscounter(karrie,fredrinn).
iscounter(roger,granger).
iscounter(roger,odette).
iscounter(vexana,layla).
iscounter(vexana,irithel).
iscounter(vexana,xavier).
iscounter(lapu_lapu,layla).
iscounter(lapu_lapu,eudora).
iscounter(aurora,leomord).
iscounter(aurora,thamuz).
iscounter(aurora,terizla).
iscounter(hilda,zilong).
iscounter(hilda,layla).
iscounter(estes,valir).
iscounter(estes,alice).
iscounter(cyclops,terizla).
iscounter(cyclops,alpha).
iscounter(johnson,alucard).
iscounter(johnson,zilong).
iscounter(moskov,thamuz).
iscounter(moskov,balmond).
iscounter(yi_sun_shin,uranus).
iscounter(yi_sun_shin,terizla).
iscounter(ruby,aldous).
iscounter(ruby,guinevere).
iscounter(alpha,layla).
iscounter(alpha,ixia).
iscounter(sun,franco).
iscounter(sun,gatotkaca).
iscounter(chou,terizla).
iscounter(chou,alpha).
iscounter(kagura,layla).
iscounter(kagura,eudora).
iscounter(natalia,novaria).
iscounter(natalia,irithel).
iscounter(gord,barats).
iscounter(gord,fredrinn).
iscounter(freya,lesley).
iscounter(freya,ixia).
iscounter(hayabusa,chang_e).
iscounter(hayabusa,cecilion).
iscounter(lolita,kimmy).
iscounter(lolita,cyclops).
iscounter(minotaur,paquito).
iscounter(minotaur,julian).
iscounter(layla,tigreal).
iscounter(layla,belerick).
iscounter(fanny,irithel).
iscounter(fanny,karrie).
iscounter(zilong,lylia).
iscounter(zilong,layla).
iscounter(eudora,wanwan).
iscounter(eudora,moskov).
iscounter(rafaela,masha).
iscounter(rafaela,barats).
iscounter(clint,moskov).
iscounter(clint,miya).
iscounter(bruno,hanabi).
iscounter(bruno,miya).
iscounter(bane,hylos).
iscounter(bane,belerick).
iscounter(franco,vale).
iscounter(franco,estes).
iscounter(franco,layla).
iscounter(akai,eudora).
iscounter(akai,odette).
iscounter(karina,layla).
iscounter(karina,hanabi).
iscounter(alucard,harley).
iscounter(alucard,aamon).
iscounter(tigreal,zilong).
iscounter(tigreal,freya).
iscounter(nana,eudora).
iscounter(nana,kadita).
iscounter(alice,cecilion).
iscounter(alice,chang_e).
iscounter(saber,layla).
iscounter(saber,eudora).
iscounter(balmond,layla).
iscounter(balmond,eudora).
iscounter(miya,saber).
iscounter(miya,eudora).
iscounter(miya,sun).
iscounter(bruno,obsidia).
iscounter(layla,obsidia).
iscounter(valentina,zetian).
iscounter(diggie,kalea).
iscounter(minotaur,kalea).
iscounter(fanny,lukas).
iscounter(valir,lukas).
iscounter(julian,lukas).
iscounter(melissa,suyou).
iscounter(badang,suyou).
iscounter(saber,zhuxin).
iscounter(fanny,zhuxin).
iscounter(barats,chip).
iscounter(tigreal,chip).
iscounter(saber,cici).
iscounter(kaja,cici).
iscounter(thamuz,nolan).
iscounter(fredrinn,nolan).
iscounter(saber,ixia).
iscounter(aamon,ixia).
iscounter(thamuz,arlott).
iscounter(fredrinn,arlott).
iscounter(saber,novaria).
iscounter(hayabusa,novaria).
iscounter(minsitthar,joy).
iscounter(khufra,joy).
iscounter(karrie,fredrinn).
iscounter(lesley,fredrinn).
iscounter(joy,julian).
iscounter(harith,julian).
iscounter(benedetta,xavier).
iscounter(hayabusa,xavier).
iscounter(natalia,xavier).
iscounter(xavier,melissa).
iscounter(nana,melissa).
iscounter(fredrinn,yin).
iscounter(badang,yin).
iscounter(karina,floryn).
iscounter(saber,floryn).
iscounter(hanabi,edith).
iscounter(wanwan,edith).
iscounter(hayabusa,valentina).
iscounter(natalia,valentina).
iscounter(hanzo,valentina).
iscounter(balmond,aamon).
iscounter(fredrinn,aamon).
iscounter(franco,aulus).
iscounter(wanwan,aulus).
iscounter(saber,natan).
iscounter(eudora,natan).
iscounter(aurora,phoveus).
iscounter(valir,phoveus).
iscounter(vexana,phoveus).
iscounter(eudora,beatrix).
iscounter(ling,beatrix).
iscounter(karrie,gloo).
iscounter(lesley,gloo).
iscounter(franco,paquito).
iscounter(kaja,paquito).
iscounter(franco,mathilda).
iscounter(minsitthar,mathilda).
iscounter(yin,yve).
iscounter(saber,yve).
iscounter(karina,yve).
iscounter(martis,brody).
iscounter(wanwan,brody).
iscounter(akai,barats).
iscounter(moskov,barats).
iscounter(x_borg,khaleed).
iscounter(chou,khaleed).
iscounter(minsitthar,benedetta).
iscounter(phoveus,benedetta).
iscounter(uranus,luo_yi).
iscounter(fredrinn,luo_yi).
iscounter(lesley,yu_zhong).
iscounter(karrie,yu_zhong).
iscounter(gusion,popol_and_kupa).
iscounter(karina,popol_and_kupa).
iscounter(valir,atlas).
iscounter(moskov,atlas).
iscounter(hanabi,carmilla).
iscounter(wanwan,carmilla).
iscounter(ling,cecilion).
iscounter(fanny,cecilion).
iscounter(martis,silvanna).
iscounter(lancelot,wanwan).
iscounter(gord,wanwan).
iscounter(cici,masha).
iscounter(thamuz,masha).
iscounter(karrie,baxia).
iscounter(lesley,baxia).
iscounter(nolan,lylia).
iscounter(ling,lylia).
iscounter(vexana,dyrroth).
iscounter(belerick,dyrroth).
iscounter(eudora,ling).
iscounter(jawhead,ling).
iscounter(martis,x_borg).
iscounter(dyrroth,x_borg).
iscounter(arlott,terizla).
iscounter(lesley,terizla).
iscounter(karrie,esmeralda).
iscounter(lesley,esmeralda).
iscounter(badang,guinevere).
iscounter(chou,guinevere).
iscounter(saber,granger).
iscounter(hayabusa,granger).
iscounter(fredrinn,khufra).
iscounter(gloo,khufra).
iscounter(wanwan,badang).
iscounter(ling,badang).
iscounter(novaria,faramis).
iscounter(pharsa,faramis).
iscounter(clint,kadita).
iscounter(beatrix,kadita).
iscounter(zilong,minsitthar).
iscounter(aulus,minsitthar).
iscounter(novaria,harith).
iscounter(pharsa,harith).
iscounter(karrie,thamuz).
iscounter(irithel,thamuz).
iscounter(lancelot,kimmy).
iscounter(saber,kimmy).
iscounter(valir,belerick).
iscounter(xavier,belerick).
iscounter(fanny,hanzo).
iscounter(lancelot,hanzo).
iscounter(arlott,hanzo).
iscounter(nolan,lunox).
iscounter(ling,lunox).
iscounter(phoveus,leomord).
iscounter(nana,leomord).
iscounter(akai,leomord).
iscounter(franco,leomord).
iscounter(hayabusa,vale).
iscounter(ling,vale).
iscounter(eudora,claude).
iscounter(franco,claude).
iscounter(martis,aldous).
iscounter(dyrroth,aldous).
iscounter(hanabi,selena).
iscounter(wanwan,selena).
iscounter(layla,kaja).
iscounter(pharsa,kaja).
iscounter(hanzo,chang_e).
iscounter(harley,chang_e).
iscounter(lancelot,hanabi).
iscounter(zilong,hanabi).
iscounter(layla,uranus).
iscounter(lesley,uranus).
iscounter(thamuz,martis).
iscounter(fredrinn,martis).
iscounter(fanny,valir).
iscounter(lancelot,valir).
iscounter(franco,gusion).
iscounter(kaja,gusion).
iscounter(harley,angela).
iscounter(ling,angela).
iscounter(edith,jawhead).
iscounter(thamuz,jawhead).
iscounter(ling,lesley).
iscounter(lancelot,lesley).
iscounter(franco,pharsa).
iscounter(zilong,pharsa).
iscounter(minsitthar,pharsa).
iscounter(fredrinn,helcurt).
iscounter(belerick,helcurt).
iscounter(gatotkaca,helcurt).
iscounter(pharsa,zhask).
iscounter(cecilion,zhask).
iscounter(karrie,hylos).
iscounter(lesley,hylos).
iscounter(ling,diggie).
iscounter(aamon,diggie).
iscounter(minsitthar,lancelot).
iscounter(phoveus,lancelot).
iscounter(minotaur,odette).
iscounter(edith,odette).
iscounter(gatotkaca,argus).
iscounter(tigreal,argus).
iscounter(kimmy,grock).
iscounter(harley,grock).
iscounter(badang,irithel).
iscounter(silvanna,irithel).
iscounter(lolita,harley).
iscounter(uranus,harley).
iscounter(diggie,gatotkaca).
iscounter(wanwan,gatotkaca).
iscounter(xavier,karrie).
iscounter(nana,karrie).
iscounter(layla,karrie).
iscounter(minsitthar,roger).
iscounter(khufra,roger).
iscounter(saber,vexana).
iscounter(aamon,vexana).
iscounter(karina,vexana).
iscounter(lesley,lapu_lapu).
iscounter(moskov,lapu_lapu).
iscounter(ling,aurora).
iscounter(kadita,aurora).
iscounter(guinevere,aurora).
iscounter(thamuz,hilda).
iscounter(uranus,hilda).
iscounter(saber,estes).
iscounter(eudora,estes).
iscounter(lancelot,cyclops).
iscounter(kagura,cyclops).
iscounter(alucard,cyclops).
iscounter(harith,johnson).
iscounter(kagura,johnson).
iscounter(lancelot,moskov).
iscounter(natalia,moskov).
iscounter(franco,yi_sun_shin).
iscounter(kaja,yi_sun_shin).
iscounter(wanwan,ruby).
iscounter(irithel,ruby).
iscounter(chou,alpha).
iscounter(gusion,alpha).
iscounter(ruby,sun).
iscounter(lesley,chou).
iscounter(pharsa,chou).
iscounter(joy,kagura).
iscounter(martis,kagura).
iscounter(minsitthar,natalia).
iscounter(kaja,natalia).
iscounter(fanny,gord).
iscounter(lancelot,gord).
iscounter(phoveus,freya).
iscounter(obsidia,freya).
iscounter(franco,hayabusa).
iscounter(kaja,hayabusa).
iscounter(ling,lolita).
iscounter(paquito,lolita).
iscounter(layla,minotaur).
iscounter(lesley,minotaur).
iscounter(karina,layla).
iscounter(ling,layla).
iscounter(kaja,fanny).
iscounter(khufra,fanny).
iscounter(franco,zilong).
iscounter(nana,zilong).
iscounter(fredrinn,eudora).
iscounter(ling,rafaela).
iscounter(hayabusa,rafaela).
iscounter(melissa,clint).
iscounter(karrie,clint).
iscounter(gatotkaca,bruno).
iscounter(fredrinn,bruno).
iscounter(vale,bane).
iscounter(xavier,bane).
iscounter(wanwan,franco).
iscounter(fanny,franco).
iscounter(badang,franco).
iscounter(nana,akai).
iscounter(diggie,akai).
iscounter(akai,karina).
iscounter(khufra,karina).
iscounter(franco,alucard).
iscounter(johnson,alucard).
iscounter(chang_e,tigreal).
iscounter(zhask,tigreal).
iscounter(zilong,nana).
iscounter(natalia,nana).
iscounter(baxia,alice).
iscounter(martis,alice).
iscounter(estes,saber).
iscounter(faramis,saber).
iscounter(lesley,balmond).
iscounter(irithel,balmond).
iscounter(pharsa,miya).
iscounter(yve,miya).