specialty(regen).
specialty(crowd_control).
specialty(finisher).
specialty(charge).
specialty(push).
specialty(damage).
specialty(burst).
specialty(poke).
specialty(initiator).
specialty(magic_damage).
specialty(mixed_damage).
specialty(guard).
specialty(chase).
specialty(control).
specialty(support).

has_specialty(alice,regen).
has_specialty(balmond,regen).
has_specialty(belerick,regen).
has_specialty(cici,regen).
has_specialty(esmeralda,regen).
has_specialty(estes,regen).
has_specialty(gloo,regen).
has_specialty(hilda,regen).
has_specialty(khaleed,regen).
has_specialty(lukas,regen).
has_specialty(phoveus,regen).
has_specialty(rafaela,regen).
has_specialty(ruby,regen).
has_specialty(uranus,regen).
has_specialty(x_borg,regen).
has_specialty(yu_zhong,regen).

has_specialty(akai,crowd_control).
has_specialty(atlas,crowd_control).
has_specialty(aulus,crowd_control).
has_specialty(aurora,crowd_control).
has_specialty(barats,crowd_control).
has_specialty(belerick,crowd_control).
has_specialty(carmilla,crowd_control).
has_specialty(chip,crowd_control).
has_specialty(gatotkaca,crowd_control).
has_specialty(grock,crowd_control).
has_specialty(khufra,crowd_control).
has_specialty(lolita,crowd_control).
has_specialty(luo_yi,crowd_control).
has_specialty(minotaur,crowd_control).
has_specialty(minsitthar,crowd_control).
has_specialty(ruby,crowd_control).
has_specialty(terizla,crowd_control).
has_specialty(tigreal,crowd_control).
has_specialty(vale,crowd_control).
has_specialty(zhuxin,crowd_control).

has_specialty(beatrix,finisher).
has_specialty(brody,finisher).
has_specialty(bruno,finisher).
has_specialty(clint,finisher).
has_specialty(fanny,finisher).
has_specialty(granger,finisher).
has_specialty(hanabi,finisher).
has_specialty(irithel,finisher).
has_specialty(ixia,finisher).
has_specialty(kagura,finisher).
has_specialty(karina,finisher).
has_specialty(karrie,finisher).
has_specialty(layla,finisher).
has_specialty(lesley,finisher).
has_specialty(martis,finisher).
has_specialty(melissa,finisher).
has_specialty(miya,finisher).
has_specialty(moskov,finisher).
has_specialty(natalia,finisher).
has_specialty(obsidia,finisher).
has_specialty(roger,finisher).
has_specialty(saber,finisher).
has_specialty(selena,finisher).
has_specialty(valentina,finisher).
has_specialty(wanwan,finisher).
has_specialty(yi_sun_shin,finisher).

has_specialty(alice,charge).
has_specialty(alpha,charge).
has_specialty(argus,charge).
has_specialty(arlott,charge).
has_specialty(badang,charge).
has_specialty(dyrroth,charge).
has_specialty(faramis,charge).
has_specialty(jawhead,charge).
has_specialty(kadita,charge).
has_specialty(kaja,charge).
has_specialty(martis,charge).
has_specialty(saber,charge).

has_specialty(bane,push).
has_specialty(helcurt,push).
has_specialty(lylia,push).
has_specialty(masha,push).
has_specialty(popol_and_kupa,push).
has_specialty(sun,push).

has_specialty(alpha,damage).
has_specialty(alucard,damage).
has_specialty(aulus,damage).
has_specialty(balmond,damage).
has_specialty(barats,damage).
has_specialty(baxia,damage).
has_specialty(beatrix,damage).
has_specialty(carmilla,damage).
has_specialty(cici,damage).
has_specialty(cyclops,damage).
has_specialty(fredrinn,damage).
has_specialty(freya,damage).
has_specialty(hanabi,damage).
has_specialty(harith,damage).
has_specialty(hilda,damage).
has_specialty(ixia,damage).
has_specialty(joy,damage).
has_specialty(kalea,damage).
has_specialty(karrie,damage).
has_specialty(khaleed,damage).
has_specialty(kimmy,damage).
has_specialty(layla,damage).
has_specialty(lukas,damage).
has_specialty(lunox,damage).
has_specialty(lylia,damage).
has_specialty(masha,damage).
has_specialty(melissa,damage).
has_specialty(miya,damage).
has_specialty(obsidia,damage).
has_specialty(paquito,damage).
has_specialty(phoveus,damage).
has_specialty(sun,damage).
has_specialty(thamuz,damage).
has_specialty(valir,damage).
has_specialty(xavier,damage).
has_specialty(yu_zhong,damage).
has_specialty(zhask,damage).
has_specialty(zhuxin,damage).
has_specialty(zilong,damage).

has_specialty(aldous,burst).
has_specialty(argus,burst).
has_specialty(arlott,burst).
has_specialty(badang,burst).
has_specialty(bane,burst).
has_specialty(benedetta,burst).
has_specialty(brody,burst).
has_specialty(bruno,burst).
has_specialty(cecilion,burst).
has_specialty(chang_e,burst).
has_specialty(claude,burst).
has_specialty(clint,burst).
has_specialty(dyrroth,burst).
has_specialty(edith,burst).
has_specialty(eudora,burst).
has_specialty(gatotkaca,burst).
has_specialty(gord,burst).
has_specialty(granger,burst).
has_specialty(guinevere,burst).
has_specialty(gusion,burst).
has_specialty(hanzo,burst).
has_specialty(harley,burst).
has_specialty(hayabusa,burst).
has_specialty(helcurt,burst).
has_specialty(irithel,burst).
has_specialty(jawhead,burst).
has_specialty(kadita,burst).
has_specialty(lancelot,burst).
has_specialty(lapu_lapu,burst).
has_specialty(leomord,burst).
has_specialty(lesley,burst).
has_specialty(ling,burst).
has_specialty(lunox,burst).
has_specialty(nana,burst).
has_specialty(natan,burst).
has_specialty(nolan,burst).
has_specialty(novaria,burst).
has_specialty(odette,burst).
has_specialty(pharsa,burst).
has_specialty(popol_and_kupa,burst).
has_specialty(roger,burst).
has_specialty(suyou,burst).
has_specialty(terizla,burst).
has_specialty(vale,burst).
has_specialty(valentina,burst).
has_specialty(wanwan,burst).
has_specialty(x_borg,burst).
has_specialty(yin,burst).
has_specialty(yve,burst).

has_specialty(aurora,poke).
has_specialty(cecilion,poke).
has_specialty(chang_e,poke).
has_specialty(diggie,poke).
has_specialty(floryn,poke).
has_specialty(gord,poke).
has_specialty(hanzo,poke).
has_specialty(harley,poke).
has_specialty(kagura,poke).
has_specialty(nana,poke).
has_specialty(novaria,poke).
has_specialty(odette,poke).
has_specialty(pharsa,poke).
has_specialty(vexana,poke).
has_specialty(yve,poke).

has_specialty(atlas,initiator).
has_specialty(franco,initiator).
has_specialty(grock,initiator).
has_specialty(hylos,initiator).
has_specialty(khufra,initiator).
has_specialty(mathilda,initiator).
has_specialty(minsitthar,initiator).
has_specialty(selena,initiator).
has_specialty(silvanna,initiator).

has_specialty(aamon,magic_damage).
has_specialty(guinevere,magic_damage).
has_specialty(gusion,magic_damage).
has_specialty(julian,magic_damage).
has_specialty(karina,magic_damage).
has_specialty(kimmy,magic_damage).
has_specialty(natan,magic_damage).
has_specialty(silvanna,magic_damage).

has_specialty(esmeralda,mixed_damage).

has_specialty(akai,guard).
has_specialty(angela,guard).
has_specialty(diggie,guard).
has_specialty(estes,guard).
has_specialty(faramis,guard).
has_specialty(floryn,guard).
has_specialty(hylos,guard).
has_specialty(lolita,guard).
has_specialty(mathilda,guard).
has_specialty(rafaela,guard).
has_specialty(valir,guard).
has_specialty(xavier,guard).

has_specialty(aamon,chase).
has_specialty(alucard,chase).
has_specialty(benedetta,chase).
has_specialty(chou,chase).
has_specialty(claude,chase).
has_specialty(fanny,chase).
has_specialty(fredrinn,chase).
has_specialty(freya,chase).
has_specialty(harith,chase).
has_specialty(hayabusa,chase).
has_specialty(joy,chase).
has_specialty(julian,chase).
has_specialty(lancelot,chase).
has_specialty(lapu_lapu,chase).
has_specialty(leomord,chase).
has_specialty(ling,chase).
has_specialty(moskov,chase).
has_specialty(natalia,chase).
has_specialty(nolan,chase).
has_specialty(paquito,chase).
has_specialty(suyou,chase).
has_specialty(thamuz,chase).
has_specialty(yi_sun_shin,chase).
has_specialty(zhask,chase).
has_specialty(zilong,chase).

has_specialty(chou,control).
has_specialty(cyclops,control).
has_specialty(edith,control).
has_specialty(eudora,control).
has_specialty(franco,control).
has_specialty(gloo,control).
has_specialty(kaja,control).
has_specialty(kalea,control).
has_specialty(vexana,control).
has_specialty(yin,control).

has_specialty(aldous,support).
has_specialty(angela,support).
has_specialty(baxia,support).
has_specialty(chip,support).
has_specialty(johnson,support).
has_specialty(luo_yi,support).